services:
  - type: web
    name: psalms-pwa
    env: node
    plan: starter
    buildCommand: cd frontend && npm install && npm run build && cd ../backend && npm install
    startCommand: node backend/src/index.js
    autoDeploy: true
